name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: preinstall
      run: pip3 install -r requirements.txt
    - name: test 
      run: ./extract_jni.py demo/app-debug.apk
